version: '3.8'

services:
  web:
    container_name: bookworm_web
    image: mwcurtis20/bookworm:stable
    build: .
    ports:
      - "8080:${FLASK_RUN_PORT}"
    environment:
      - FLASK_RUN_HOST=${FLASK_RUN_HOST}
      - FLASK_RUN_PORT=${FLASK_RUN_PORT}
      - SECRET_KEY=${SECRET_KEY}
      - GOOGLE_GEMINI_API_KEY=${GOOGLE_GEMINI_API_KEY}
      - ENABLE_GEMINI_API=${ENABLE_GEMINI_API}
      - GEMINI_MODEL=${GEMINI_MODEL}
    labels:
      - "com.centurylinklabs.watchtower.scope=bookworm"
    networks:
      - internal_bookworm_net
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/healthcheck"]
      interval: 30s
      timeout: 10s
      retries: 3
  watchtower:
    image: containrrr/watchtower
    container_name: bookworm_watchtower
    environment:
      - REPO_USER=${REPO_USER}
      - REPO_PASS=${REPO_PASS}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - "com.centurylinklabs.watchtower.scope=bookworm"
    networks:
      - internal_bookworm_net
    command: --debug --scope bookworm --cleanup --interval 300
    restart: unless-stopped
networks:
  internal_bookworm_net:
    external: false